CREATE DATABASE IF NOT EXISTS ejemplo_alumnos
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE ejemplo_alumnos;

CREATE TABLE IF NOT EXISTS personas (
  Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Nombre VARCHAR(80) NOT NULL,
  Apellido VARCHAR(80) NOT NULL,
  Dni VARCHAR(20) NOT NULL UNIQUE
) ENGINE=InnoDB;
